#!/usr/local/bin/perl
use HTTP::Daemon::SSL;

$d = new HTTP::Daemon::SSL
	SSL_cert_file => '/git/certs/server-cert.pem',
	SSL_key_file => '/git/certs/server-key.pem',
	LocalPort => 443 or die;
while($r = ($c=$d->accept)->get_request) {
	my $o;
	$o .= `$_` foreach glob '/git/webroot/*';
	$c->send_response(new HTTP::Response 200, 'OK', HTTP::Headers->new('Content-Type' => 'text/plain'), $o);
	$c->close;
}
